In [2]:
import cv2
import numpy as np

In [3]:
path = r'D:\E_image\Pre_X-ray(Lateral)(512,512).bmp'
image = cv2.imread(path)
print(image.shape)
x=256
y=256
w=256
h=256
crop_img = image[y:y+h, x:x+w]



(512, 512, 3)


In [282]:
cv2.imshow("cropped", crop_img)
cv2.waitKey(0)
cv2.imshow("cropped", image)
cv2.waitKey(0)

-1

In [283]:
img = cv2.cvtColor(crop_img, cv2.COLOR_BGR2GRAY)
dst = cv2.GaussianBlur(img, (31,31), 0)
cv2.imshow("cropped1", dst)
cv2.waitKey(0)
ret, th2 = cv2.threshold(dst, 80, 255, cv2.THRESH_BINARY)
print(th2.shape)
cv2.imshow("cropped", th2)
cv2.waitKey(0)

(256, 256)


-1

In [284]:
contours,hierarchy = cv2.findContours(th2,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
crop=crop_img
zznp=np.zeros((256, 256,3),dtype=np.uint8)
cv2.drawContours(zznp,contours,-1,(0,0,255),3)
cv2.imshow("cropped", zznp)
cv2.waitKey(0)
print(contours)

(array([[[224,   0]],

       [[224,   2]],

       [[227,   5]],

       [[229,   5]],

       [[231,   3]],

       [[231,   0]]], dtype=int32), array([[[131,   0]],

       [[131,   3]],

       [[130,   4]],

       [[130,  15]],

       [[131,  16]],

       [[131,  22]],

       [[130,  23]],

       [[130,  24]],

       [[128,  26]],

       [[128,  27]],

       [[125,  30]],

       [[124,  30]],

       [[123,  31]],

       [[122,  31]],

       [[121,  32]],

       [[119,  32]],

       [[118,  33]],

       [[115,  33]],

       [[114,  34]],

       [[110,  34]],

       [[109,  35]],

       [[101,  35]],

       [[100,  36]],

       [[ 98,  36]],

       [[ 97,  37]],

       [[ 97,  41]],

       [[ 98,  42]],

       [[ 98,  45]],

       [[ 97,  46]],

       [[ 97,  47]],

       [[ 96,  48]],

       [[ 95,  48]],

       [[ 93,  50]],

       [[ 91,  50]],

       [[ 90,  51]],

       [[ 88,  51]],

       [[ 87,  52]],

       [[ 84,  52]],

       [[ 79,  47

In [285]:
imgg = cv2.cvtColor(zznp, cv2.COLOR_BGR2GRAY)

ret, th3 = cv2.threshold(imgg, 50, 255, cv2.THRESH_BINARY)

num_objects, labels = cv2.connectedComponents(th3)
print(num_objects)
print(labels)

output = np.zeros((img.shape[0], img.shape[1], 3), np.uint8)
a=labels.shape
print(a)
cc =np.zeros((num_objects))
for l in range(1, num_objects):
    for i in range(1, a[0]):
        for j in range(1, a[1] ):
                if labels[i,j]==l:
                    cc[l]+=1 
max=0
label_index=0
for l in range(1, num_objects):
    if cc[l]>max :
        max=cc[l]
        label_index=l
mask = labels==label_index
output[:, :, 0][mask] = np.random.randint(0, 255)
output[:, :, 1][mask] = np.random.randint(0, 255)
output[:, :, 2][mask] = np.random.randint(0, 255)
imggg = cv2.cvtColor(output, cv2.COLOR_BGR2GRAY)
ret, th4 = cv2.threshold(imggg, 50, 255, cv2.THRESH_BINARY)

index=np.zeros((2))
for i in range(1, 256):
    for j in range(1, 256):
        if th4[a[0]-i][a[1]-j]!=0:
            index=(i,j)




print(index)
for i in range(0, a[0]):
    for j in range(0, a[1] ):
        if i<index[1] :
            th4[i][j]=0
cv2.imshow("cropped", th4)
cv2.waitKey(0)
print(th4)
crop_img[:, :, 0][th4] = 0
crop_img[:, :, 1][th4] = 0
crop_img[:, :, 2][th4] = 0

contours,hierarchy = cv2.findContours(th4,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(crop_img,contours,-1,(0,0,255),3)
cv2.imshow("cropped",crop_img)
cv2.waitKey(0)

4
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(256, 256)
(255, 127)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


-1

In [293]:
crop_img3= image[0:256, 0:256]
cv2.imshow("cropped",crop_img2)
cv2.waitKey(0)
img = cv2.cvtColor(crop_img2, cv2.COLOR_BGR2GRAY)

In [308]:
img = cv2.cvtColor(crop_img3, cv2.COLOR_BGR2GRAY)
ret, th5 = cv2.threshold(img,100 , 255, cv2.THRESH_TOZERO)

ret, th5 = cv2.threshold(th5,225, 255, cv2.THRESH_BINARY)
print(th5.shape)
cv2.imshow("cropped", th5)
cv2.waitKey(0)

(256, 256)


-1

In [313]:
# detect circles in the image
circles = cv2.HoughCircles(th5, cv2.HOUGH_GRADIENT, 1.3, 5,param1=50,param2=20,minRadius=0,maxRadius=19)
# ensure at least some circles were found
if circles is not None:
	# convert the (x, y) coordinates and radius of the circles to integers
	circles = np.round(circles[0, :]).astype("int")
	# loop over the (x, y) coordinates and radius of the circles

	for (x, y, r) in circles:
		# draw the circle in the output image, then draw a rectangle
		# corresponding to the center of the circle
		cv2.circle(crop_img3, (x, y), r, (0, 255, 0), 4)
		cv2.rectangle(crop_img3, (x - 5, y - 5), (x + 5, y + 5), (0, 128, 255), -1)
	# show the output image
	cv2.imshow("output", crop_img3)
	cv2.waitKey(0)

In [314]:
cv2.imshow("Final", image)
cv2.waitKey(0)